spring.application.name=GhostLeadAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/ghostlead
spring.datasource.username=ghostlead
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
